name = input("Enter your name: ")
print(f"Hello {name}!")
age = input("Enter your age: ")
print(f"You are {age} years old.")
place = input("Where do you live: ")
print(f"You live in {place}.")
programming_language = input("Which programming language are you revising? ")
print(f"So, you are revising {programming_language}.")
print(type(age))